sudo: required
dist: trusty
language: cpp
notifications:
  email: false


language: python

python:
  #- "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
os:
  - linux
before_install:
  - sudo add-apt-repository -y ppa:beineri/opt-qt59-trusty

install:
  - pip install python-xlib codecov coverage
  - sudo apt-get update
  - sudo apt-get install -qq qt59base; 
  - sudo apt-get -y install qt59declarative qt59tools
  - sudo apt-get install xsel
  - source /opt/qt59/bin/qt59-env.sh;
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - xauth generate :99.0 . trusted
  # Clone test apps
  - git init apps
  - cd apps
  - git remote add -f origin https://github.com/pywinauto/PywinautoTestapps/
  - git config core.sparseCheckout true
  - echo "MouseTester/source" >> .git/info/sparse-checkout
  - echo "SendKeysTester/source" >> .git/info/sparse-checkout
  - git pull origin master
  # Build test apps
  - cd MouseTester/source
  - qmake
  - make
  - chmod a+x mousebuttons
  - cp mousebuttons ../
  - cd $TRAVIS_BUILD_DIR
  - cd apps/SendKeysTester/source
  - qmake
  - make
  - chmod a+x send_keys_test_app
  - cp send_keys_test_app ../
  - cd $TRAVIS_BUILD_DIR

script:
  - coverage run -a --include=pywinauto/mouse.py pywinauto/unittests/test_mouse.py
  - coverage run -a --include=pywinauto/linux/keyboard.py pywinauto/unittests/test_keyboard.py
  - coverage run -a --include=pywinauto/linux/clipboard.py pywinauto/unittests/test_clipboard_linux.py

after_success:
  - codecov