name: tests on legacy macOS

on: [push]

jobs:
  build:
    runs-on: macOS-10.14
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install six
        pip install codecov coverage pyobjc==5.2 python-xlib
    - name: Clone test apps
      run: |
        git init apps
        cd apps
        git remote add -f origin https://github.com/zemtsov-artem/PywinautoTestapps/
        git config core.sparseCheckout true
        echo "MouseTester/macos" >> .git/info/sparse-checkout
        echo "SendKeysTester/macos" >> .git/info/sparse-checkout
        git pull origin azemtsov/macos_test_apps
        git checkout origin/azemtsov/macos_test_apps
        cd ..
    - name: Build test apps
      run: |
        cd apps/MouseTester/macos
        sudo hdiutil attach mousebuttons.dmg
        sudo cp -R /Volumes/mousebuttons/mousebuttons.app /Applications
        sudo hdiutil detach /Volumes/mousebuttons/
        cd ../../../
        cd apps/SendKeysTester/macos
        sudo hdiutil attach send_keys_test_app.dmg
        sudo cp -R /Volumes/send_keys_test_app/send_keys_test_app.app /Applications
        sudo hdiutil detach /Volumes/send_keys_test_app/
        cd ../../../
    - name: Test with GUI
      run: |
        coverage run -a --source=pywinauto/macos pywinauto/unittests/test_application_macos.py
        coverage run -a --source=pywinauto/macos pywinauto/unittests/test_ax_element_info_macos.py
        coverage run -a --include=pywinauto/mouse.py pywinauto/unittests/test_mouse.py
        coverage run -a --include=pywinauto/macos/keyboard_helper.py pywinauto/unittests/test_keyboard.py
    - name: Submit Code Coverage
      run: |
        codecov
